name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install 32-bit g++ and cmake
      run: sudo apt install g++-multilib cmake
    - name: Setup Makefile
      run: cmake -B out
    - name: Build
      run: cmake --build out
    - name: Run
      run: ./out/spider

  build-win:
    runs-on: windows-2022
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - uses: actions/checkout@v4
    - name: Generate solution
      run: cmake -B out -A Win32
    - name: Compile
      working-directory: ./out
      run: msbuild spider.sln /p:Platform=Win32 /p:Configuration=Release
    - name: Run
      working-directory: ./out
      run: Release\spider.exe
